language: cpp
compiler: 
 - g++
env:
  matrix:
  - BUILD_TYPE: RELEASE
    BUILD_OUTPUT: Release
  - BUILD_TYPE: DEBUG
    BUILD_OUTPUT: Debug
addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
   - gcc-4.8
   - g++-4.8
script:
 - make all CXX="g++-4.8" CC="g++-4.8" CONFIG="${BUILD_TYPE}"
 - PWD=$(pwd)
 - ./tests/$BUILD_OUTPUT/tests $PWD/src/server/$BUILD_OUTPUT/scache $PWD/testcases/