language: cpp
compiler: 
 - g++
install:
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq g++-4.8
script:
 - make tests CXX="g++-4.8" CC="g++-4.8"
 - ./tests/Debug/tests