language: cpp
compiler: 
 - g++
env:
  matrix:
  - BUILD_TYPE: RELEASE
    BUILD_OUTPUT: Release
  - BUILD_TYPE: DEBUG
    BUILD_OUTPUT: Debug

install:
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq g++-4.8
script:
 - make all CXX="g++-4.8" CC="g++-4.8" CONFIG="${BUILD_TYPE}"
 - ./tests/$BUILD_OUTPUT/tests ./src/server/$BUILD_OUTPUT/scache ./testcases/