name: build and test

on:
  push:
  schedule:
    - cron:  '*/5 * * * *'


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release: ["Release", "Debug"]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        make all CONFIG=${{ matrix.release }}
    - name: Main tests
      run: |
        PWD=$(pwd)
        ./tests/${{ matrix.release }}/tests $PWD/src/server/${{ matrix.release }}/scache $PWD/testcases/
    - name: valgrind test
      run: |
        PWD=$(pwd)
        sudo apt-get install valgrind
        valgrind --leak-check=full --show-leak-kinds=all ./tests/${{ matrix.release }}/tests $PWD/src/server/${{ matrix.release }}/scache $PWD/testcases/
    - name: Spam test
      run: |
        echo "todo"
    - name: Valgrind monitoring test
      run: |
        sudo mkdir -p /var/lib/scache/ &
        sudo apt-get install psmisc
        wait
        sudo chmod 0777 /var/lib/scache/ -R

        function query {
          sleep 2
          for i in {1..50}
          do
            curl 127.0.0.1:8082/conn &
          done

          sleep 110

          killall curl
        }

        query &

        timeout --kill-after=3 --preserve-status 2m valgrind --leak-check=full --show-leak-kinds=all src/server/${{ matrix.release }}/scache -B 127.0.0.1:8082
